apiVersion: apps/v1
kind: Deployment
metadata:
  name: learningwsc
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: learningwsc
  template:
    metadata:
      labels:
        app: learningwsc
    spec:
      containers:
      - name: learningwsc
        image: ckacr001.azurecr.cn/learningwsc:281
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: learningwsc
spec:
  type:
    LoadBalancer
  selector:
    app: learningwsc
  ports:
  - port: 80
    targetPort: 80

